name: Build And Deploy

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 22.2.0
        uses: actions/setup-node@v2
        with:
          node-version: "22.2.0"

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Create Server .env file
        run: |
          cd server
          echo "${{ secrets.SERVER_ENV }}" > .env

      - name: Install Dependencies
        run: |
          cd server
          npm ci

      - name: Start Server
        run: |
          cd server
          pm2 restart server || pm2 start npm --name "server" -- start